import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Libre_Baskerville, Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["800", "900", "500", "700"],
  variable: "--font-montserrat",
});

const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-libre-baskerville",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${libreBaskerville.variable} ${montserrat.variable}`}
    >
      <body
        className={
          "font-libreBaskerville antialiased max-w-screen-2xl 2xl:mx-auto 2xl:border-x-2"
        }
      >
        {children}
      </body>
      <Toaster />
    </html>
  );
}
